sudo: false
language: node_js
node_js:
- 5.8.0
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: 'never'
    on_failure: 'never'
before_install:
- npm config set progress=false
- npm install -g npm@^3
install:
- npm i
- npm run bs
script:
- npm start
