sudo: false
language: node_js
node_js:
  - 6
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
    - packages/boiler-addon-assemble-isomorphic-memory/node_modules
    - packages/boiler-addon-assemble-isomorphic-static/node_modules
    - packages/boiler-addon-assemble-middleware/node_modules
    - packages/boiler-addon-assemble-nunjucks/node_modules
    - packages/boiler-addon-isomorphic-tools/node_modules
    - packages/boiler-addon-webpack-babel/node_modules
    - packages/boiler-addon-webpack-isomorphic/node_modules
    - packages/boiler-addon-webpack-karma/node_modules
    - packages/boiler-addon-webpack-loaders-base/node_modules
    - packages/boiler-addon-webpack-loaders-optimize/node_modules
    - packages/boiler-addon-webpack-styles/node_modules
    - packages/boiler-config-assemble/node_modules
    - packages/boiler-config-base/node_modules
    - packages/boiler-config-eslint/node_modules
    - packages/boiler-config-webpack/node_modules
    - packages/boiler-core/node_modules
    - packages/boiler-preset-base/node_modules
    - packages/boiler-preset-plus/node_modules
    - packages/boiler-task-assemble/node_modules
    - packages/boiler-task-babel/node_modules
    - packages/boiler-task-browser-sync/node_modules
    - packages/boiler-task-clean/node_modules
    - packages/boiler-task-copy/node_modules
    - packages/boiler-task-eslint/node_modules
    - packages/boiler-task-karma/node_modules
    - packages/boiler-task-mocha/node_modules
    - packages/boiler-task-nodemon/node_modules
    - packages/boiler-task-selenium/node_modules
    - packages/boiler-task-webpack/node_modules
    - packages/boiler-utils/node_modules
notifications:
  email:
    on_success: never
    on_failure: never
before_install:
  - npm config set progress=false
  - npm install -g npm@^3
  - npm install -g snyk
install:
  - npm i
  - 'npm run lerna:bootstrap'
  - npm run compile
script:
  - npm start
  - npm test
  - ./run-snyk.sh test
